# Generated by Django 4.0.4 on 2022-05-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0011_alter_comments_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
