# Generated by Django 4.0.4 on 2022-05-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0012_alter_comments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='preview_content',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut diam et dolor dignissim malesuada finibus pretium nibh. Phasellus lobortis metus quis posuere ultricies. Cras et venenatis urna, nec posuere ligula. Ut mattis semper enim non lobortis. Cras euismod luctus odio nec cursus. Sed dignissim placerat tincidunt. Nullam convallis convallis neque vel gravida. ', max_length=1000, verbose_name='Тизер'),
        ),
    ]
