# Generated by Django 4.0.4 on 2022-05-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0013_news_preview_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='preview_content',
            field=models.CharField(max_length=1000, verbose_name='Тизер'),
        ),
    ]
